/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MairieRouteImport } from './routes/mairie'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CommerceSlugRouteImport } from './routes/commerce.$slug'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MairieRoute = MairieRouteImport.update({
  id: '/mairie',
  path: '/mairie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceSlugRoute = CommerceSlugRouteImport.update({
  id: '/commerce/$slug',
  path: '/commerce/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mairie': typeof MairieRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/commerce/$slug': typeof CommerceSlugRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mairie': typeof MairieRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/commerce/$slug': typeof CommerceSlugRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mairie': typeof MairieRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/commerce/$slug': typeof CommerceSlugRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mairie'
    | '/pro'
    | '/reset-password'
    | '/commerce/$slug'
    | '/site/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mairie'
    | '/pro'
    | '/reset-password'
    | '/commerce/$slug'
    | '/site/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mairie'
    | '/pro'
    | '/reset-password'
    | '/commerce/$slug'
    | '/site/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MairieRoute: typeof MairieRoute
  ProRoute: typeof ProRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CommerceSlugRoute: typeof CommerceSlugRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mairie': {
      id: '/mairie'
      path: '/mairie'
      fullPath: '/mairie'
      preLoaderRoute: typeof MairieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce/$slug': {
      id: '/commerce/$slug'
      path: '/commerce/$slug'
      fullPath: '/commerce/$slug'
      preLoaderRoute: typeof CommerceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MairieRoute: MairieRoute,
  ProRoute: ProRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CommerceSlugRoute: CommerceSlugRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
